# Generated by Django 2.1.2 on 2018-10-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181025_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(max_length=2, verbose_name='Tipo de documento'),
        ),
    ]
