# Generated by Django 2.1.2 on 2018-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181025_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(max_length=2, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identity_document',
            field=models.CharField(max_length=15, null=True, verbose_name='Número de documento'),
        ),
    ]
